= aerospike-operator
aerospike-operator manages Aerospike clusters atop Kubernetes, automating their creation and administration.
:icons: font
:toc:

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

image:https://img.shields.io/badge/status-development-blue.svg["Status"]
image:https://quay.io/repository/travelaudience/aerospike-operator/status["Docker Repository on Quay", link="https://quay.io/repository/travelaudience/aerospike-operator"]

WARNING: `aerospike-operator` is currently _alpha_, and is under active
development. One should expect breaking changes to the API and behavior to be
introduced at any moment.

== Prerequisites

* Kubernetes 1.10+

WARNING: Versions of Kubernetes prior to 1.10.5 are affected by
https://github.com/kubernetes/kubernetes/issues/62382[#62382], which can cause failed backup and restore jobs to
re-create pods indefinitely. Hence, running `aerospike-operator` on top of Kubernetes 1.10.5 or later is strongly
recommended.

NOTE: Support for Kubernetes 1.11 is being planned and will be implemented as
soon as it is generally available.

== Documentation

One can find comprehensive usage documentation in the `docs/usage` directory of
this repository. Existing documentation covers the following topics:

1. <<./docs/usage/00-installation-guide.adoc#,Installation Guide>> provides
   instructions on how to install and configure `aerospike-operator`.
1. <<./docs/usage/10-managing-clusters.adoc#,Managing Clusters>> includes
   details on how to create, configure, inspect and scale Aerospike clusters.
1. <<./docs/usage/20-backing-up-namespaces.adoc#,Backing-up Namespaces>> details
   how to create backups of data in an Aerospike cluster.
1. <<./docs/usage/30-restoring-namespaces.adoc#,Restoring Namespaces>> provides
   instructions on how to restore the abovementioned backups.
1. <<./docs/usage/40-upgrading-clusters.adoc#,Upgrading Clusters>> details how
   to upgrade an Aerospike cluster to a later version.
1. <<./docs/usage/50-upgrading-aerospike-operator.adoc#,Upgrading `aerospike-operator`>>
   describes how to upgrade the version of `aerospike-operator` itself.
1. <<./docs/usage/80-metrics.adoc#,Metrics>> includes information on how to
   consume the metrics exported by `aerospike-operator`.
1. <<./docs/usage/90-limitations.adoc#,Limitations>> provides a list of
   limitations that exist in the current version of `aerospike-operator`.

In addition to these documents, and in order to understand the design and
architecture of `aerospike-operator`, one should have a look at the `docs/design/`
directory of this repository.
