version: 2.1

parameters:
  dirs:
    type: string
    default: foo

jobs:
  print_dirs:
    docker:
      - image: cimg/base:2024.10
    steps:
      - run: echo << pipeline.parameters.dirs >>

workflows:
  print:
    jobs:
      - print_dirs
