version: 2.1

parameters:
  dirs:
    type: string
    default: foo

jobs:
  print_dirs:
    parameters:
        dirs: string
        default: foo
    docker:
      - image: cimg/base:2024.10
    steps:
      - run: echo << parameters.dirs >>

workflows:
  print:
    jobs:
      - print_dirs:
          dirs: << pipeline.parameters.dirs >>
