= Building aerospike-operator
This document describes how to build and run aerospike-operator.
:icons: font
:toc:

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Pre-requisites

To build `aerospike-operator`, one needs to install the following software in their workstation:

* Docker
* Go
* `kubectl`
* `make`
* https://github.com/GoogleContainerTools/skaffold[`skaffold`]

To run `aerospike-operator` one needs a Kubernetes 1.13+ cluster. The build toolchain includes `skaffold` profiles that allow for easy deployment in GKE and Minikube clusters.

=== Google Kubernetes Engine

To use the GKE profile, one needs to have the following:

* A Google Cloud Platform project.
** The https://cloud.google.com/container-builder/docs/[Cloud Container Builder API] must be enabled for this project.
* A Google Cloud Platform service account with at least the following IAM roles:
** `roles/cloudbuild.builds.builder`
** `roles/container.admin`
** `roles/storage.admin`
* A JSON file containing the credentials for the abovementioned service account.
** It is assumed the JSON file is located at `<path-to-credentials>`.
* The https://cloud.google.com/sdk/[Google Cloud SDK] (i.e. `gcloud`) installed in one's workstation.
** One should set the value of the `GOOGLE_APPLICATION_CREDENTIALS` environment variable to `/path/to/key.json`.
* A Google Kubernetes Engine 1.13+ cluster.
** `kubectl` must be configured to connect to this cluster.
** One must also run https://cloud.google.com/sdk/gcloud/reference/auth/configure-docker[`gcloud auth configure-docker`] in order to register `gcloud` as a Docker credential helper.
** Finally, one must manually bind the `cluster-admin` cluster role in the GKE cluster to the abovementioned service account, as described in https://cloud.google.com/kubernetes-engine/docs/how-to/role-based-access-control#setting_up_role-based_access_control[Role-Based Access Control].
* A Google Cloud Storage bucket.

=== Minikube

To use the Minikube profile, one only needs to have a Minikube cluster running Kubernetes 1.13+.

== Cloning the repository

To start developing, one should clone the repository into one's `$GOPATH`:

[source,bash]
----
$ git clone \
    git@github.com:travelaudience/aerospike-operator.git \
    $GOPATH/src/github.com/travelaudience/aerospike-operator
$ cd $GOPATH/src/github.com/travelaudience/aerospike-operator
----

== Generating code

Part of working with custom resource definitions involves generating code using https://github.com/kubernetes/code-generator[`k8s.io/code-generator`]. To run code generation, one should run the following command:

[source,bash]
----
$ make gen
----

This will create the following files in the project tree, which are ignored by Git:

[source,bash]
----
pkg
├── apis
│   └── aerospike
│       └── v1alpha1
│           └── zz_generated.deepcopy.go (GENERATED)
│       └── v1alpha2
│           └── zz_generated.deepcopy.go (GENERATED)
└── client (GENERATED)
----

TIP: The code generation step should be run after cloning the project and whenever a modification to `pkg/apis` is made.

== Running `aerospike-operator`

`aerospike-operator` must run inside a Kubernetes cluster. `skaffold` is used in order to ease the deployment.

=== Google Kubernetes Engine

To deploy `aerospike-operator` to the GKE cluster targeted by the current `kubectl` context one may run:

[source,bash]
----
$ PROFILE=gke \
  PROJECT_ID=<project-id> \
  make skaffold
----

NOTE: One must replace `<project-id>` with the ID of the Google Cloud Platform project in use.

This will create a single `aerospike-operator` pod inside the `aerospike-operator` namespace and start streaming its logs.

----
$ PROFILE=gke \
  PROJECT_ID=<project-id> \
  make skaffold
(...)
time="2018-07-22T21:27:04Z" level=info msg="aerospike-operator is starting" version=0.8.0
(...)
time="2018-07-22T21:27:11Z" level=info msg="started workers" controller=aerospikecluster
----

To re-deploy `aerospike-operator` after making local changes to the code, one simply needs to re-run the command above.

=== Minikube

To deploy `aerospike-operator` to the Minikube cluster targeted by the current `kubectl` context one may run:

[source,bash]
----
$ PROFILE=minikube \
  make skaffold
----

This will create the same pod described above. To re-deploy `aerospike-operator` after making local changes to the code, one simply needs to re-run the command above.

== Running the end-to-end test suite

=== Google Kubernetes Engine

To run the end-to-end test suite against a running instance of `aerospike-operator`, one may run:

[source,bash]
----
$ GCS_BUCKET_NAME=<bucket-name> \
  PROFILE=gke \
  PROJECT_ID=<project-id> \
  STORAGE_ADMIN_KEY_JSON_FILE=<path-to-credentials> \
  make test.e2e
----

This will create a pod named `aerospike-operator-e2e` in the `aerospike-operator-e2e` namespace and start streaming its logs.
By the time the end-to-end test suite finishes, one will see the following message in the logs:

[source,bash]
----
(...)
Ran 36 of 36 Specs in 2883.012 seconds
SUCCESS! -- 36 Passed | 0 Failed | 0 Flaked | 0 Pending | 0 Skipped
(...)
----

=== Minikube

Running the end-to-end test suite in Minikube is currently not supported, as support for Minikube is primarily targeted at providing a fast way around development and smoke testing.
