[[toc]]
= Backup & Restore
This document describes how backup and restore operations are performed by aerospike-operator.
:icons: font
:toc:

== Backup

`aerospike-operator` supports backing-up a single Aerospike namespace to cloud storage
footnoteref:[gcs-only,Currently only Google Cloud Storage is supported]. A backup is
triggered by the creation of an `AerospikeNamespaceBackup` resource such as

[[AerospikeNamespaceBackup]]
[source,yaml]
----
apiVersion: aerospike.travelaudience.com/v1alpha1
kind: AerospikeNamespaceBackup
metadata:
  name: aerospike-backup-0
  namespace: kubernetes-namespace-0
spec:
  target:
    cluster: aerospike-cluster-0
    namespace: aerospike-namespace-0
  storage:
    type: gcs
    bucket: target-gcs-bucket
    secret: gcs-secret
----

Creating this resource will cause `aerospike-operator` to create a backup for
the `aerospike-namespace-0` namespace of the `aerospike-cluster-0` cluster, and
to upload it to the `target-gcs-bucket` GCS bucket using the credentials
specified in the `gcs-secret` secret. The backup will be named
`aerospike-backup-0`, and will result in two files being created in the
specified bucket: `aerospike-backup-0.asb.gz` and
`aerospike-backup-0.asb.gz.meta`.

NOTE: Before creating an `AerospikeNamespaceBackup`, the user must make sure
that the target GCS bucket exists, and that the `gcs-secret` secret contains the
required <<gcs-credentials,credentials>> in the expected format.

IMPORTANT: Any files with these names that may previously exist in the bucket
will be _replaced_ (including any previous backups with the same name). The user
should choose unique names for the backups and make sure they do not clash with
important files that may exist in the target bucket.

To backup an Aerospike namespace, `aerospike-operator` uses the
https://www.aerospike.com/docs/tools/backup/asbackup.html[`asbackup`] tool. In
order to make the backup operation faster and cheaper, `aerospike-operator`
streams the backup data to the target bucket as it becomes available (as opposed
to temporarily storing the backup data in a persistent volume and uploading only
when `asbackup` finishes).

== Restore

Restoring a single Aerospike namespace from cloud storage is also supported
footnoteref:[gcs-only]. A restore
operation is triggered by the creation of an `AerospikeNamespaceRestore`
resource such as

[source,yaml]
----
apiVersion: aerospike.travelaudience.com/v1alpha1
kind: AerospikeNamespaceRestore
metadata:
  name: aerospike-backup-0
  namespace: kubernetes-namespace-0
spec:
  target:
    cluster: aerospike-cluster-0
    namespace: aerospike-namespace-0
  storage:
    type: gcs
    bucket: source-gcs-bucket
    secret: gcs-secret
----

However, before creating this resource one must make sure that:

* The target Aerospike cluster and namespace already exist.
* The source GCS bucket exists.
* The `gcs-secret` secret contains the required <<gcs-credentials,credentials>>
  in the expected format.
* The name given to the `AerospikeNamespaceRestore` resource matches the name
  of the backup file in the source bucket _without the `.asb.gz` extension_.

To restore an Aerospike namespace, `aerospike-operator` uses the
https://www.aerospike.com/docs/tools/backup/asrestore.html[`asrestore`] tool. In
order to make the restore operation faster and cheaper, `aerospike-operator`
streams the data being restored from the target bucket (as opposed to
downloading it to a persistent volume and restoring only when the download
finishes).

`aerospike-operator` also supports restoring backup data to an Aerospike namespace
whose name doesn't match the original name of the namespace. This can be useful in
scenarios where "renaming" an Aerospike namespace is desired. In order to achieve this,
`aerospike-operator` stores the name of the original Aerospike namespace alongside the
backup data (i.e. in the `<backup-name>.asb.gz.meta` file). When restoring,
`aerospike-operator` reads this metadata and passes both the original name (coming
from the metadata) and the new name (coming from the `AerospikeNamespaceRestore` resource)
to `asrestore`. For instance, when creating the example `AerospikeNamespaceBackup`
given <<AerospikeNamespaceBackup,above>>, the created `aerospike-backup-0.asb.gz.meta`
file will store the original name of the Aerospike namespace (`aerospike-namespace-0`)
in the metadata file. Then, when creating an `AerospikeNamespaceRestore` with a different target Aerospike
namespace such as

[source,yaml]
----
apiVersion: aerospike.travelaudience.com/v1alpha1
kind: AerospikeNamespaceRestore
metadata:
  name: aerospike-backup-0
  namespace: kubernetes-namespace-0
spec:
  target:
    cluster: aerospike-cluster-1
    namespace: aerospike-namespace-1
  storage:
    type: gcs
    bucket: source-gcs-bucket
    secret: gcs-secret
----

`aerospike-operator` will configure `asrestore` to restore data to the Aerospike
namespace named `aerospike-namespace-1` by making use of the
`--namespace` https://www.aerospike.com/docs/tools/backup/asrestore.html#data-selection-options[flag].

== Google Cloud Storage

[[gcs-credentials]]
=== Credentials

Both backup and restore operations require credentials for accessing the
source/target bucket. For Google Cloud Storage, this corresponds to a JSON file
containing the credentials of a
https://cloud.google.com/iam/docs/understanding-service-accounts[GCP service account].
This JSON file must be stored in a
https://kubernetes.io/docs/concepts/configuration/secret/[Kubernetes secret]
containing a `key.json` field:

[source,yaml]
----
apiVersion: v1
data:
  key.json: [DATA]
kind: Secret
metadata:
  name: gcs-secret
  namespace: kubernetes-namespace-0
type: Opaque
----

NOTE: Since Kubernetes secrets are namespaced resources, this secret must exist
in the same Kubernetes namespace where the `AerospikeNamespaceBackup` and
`AerospikeNamespaceRestore` resources are created.

=== Permissions

The service account used for backup and restore operations must have at least
the `roles/storage.admin`
https://cloud.google.com/storage/docs/access-control/iam-roles[IAM role].
