---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aerospike-operator-e2e
rules:
- apiGroups: [""]
  resources:
  - namespaces
  verbs:
  - create
  - delete
- apiGroups: [""]
  resources:
  - persistentvolumeclaims
  verbs:
  - get
- apiGroups: [""]
  resources:
  - pods
  - nodes
  verbs:
  - get
  - list
- apiGroups: [""]
  resources:
  - secrets
  verbs:
  - create
  - get
- apiGroups:
  - aerospike.travelaudience.com
  resources:
  - aerospikeclusters
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - aerospike.travelaudience.com
  resources:
  - aerospikenamespacebackups
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups: 
  - aerospike.travelaudience.com
  resources:
  - aerospikenamespacerestores
  verbs:
  - create
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aerospike-operator-e2e
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aerospike-operator-e2e
subjects:
- kind: ServiceAccount
  name: aerospike-operator-e2e
  namespace: aerospike-operator-e2e
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: aerospike-operator
  name: aerospike-operator-e2e
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: aerospike-operator
  name: aerospike-operator-e2e
  namespace: aerospike-operator-e2e
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: aerospike-operator
  name: aerospike-operator-e2e
  namespace: aerospike-operator-e2e
data:
  key.json: |
    __BASE64_ENCODED_STORAGE_ADMIN_KEY_JSON__
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: aerospike-operator
  name: aerospike-operator-e2e
  namespace: aerospike-operator-e2e
spec:
  containers:
  - name: aerospike-operator-e2e
    image: gcr.io/__PROJECT_ID__/aerospike-operator-e2e
    imagePullPolicy: IfNotPresent
    args:
    - /aerospike-operator-e2e
    - -ginkgo.flakeAttempts=3
    - -ginkgo.focus=__FOCUS__
    - -ginkgo.progress
    - -ginkgo.skip=__SKIP__
    - -ginkgo.v
    - -gcs-bucket-name=__GCS_BUCKET_NAME__
    - -gcs-secret-name=aerospike-operator-e2e
    - -gcs-secret-namespace=aerospike-operator-e2e
    - -gcs-secret-key=key.json
    - -test.timeout=7200s
    - -test.v
  restartPolicy: Never
  serviceAccountName: aerospike-operator-e2e
